# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52e0ec8f0ca35ba5d31ed5761b9d659b4f683b1020613ed7ca024261f432430ffad87458f0febe16d21c091a946bb5b19ee07b07248b168b98c3156fe2599e0b

test:
  secret_key_base: aac50f60173dc47e7347eadeebb2c9eb32ed1d4ee4ee9c97b0b8c746f4578655f08f3805509b5ca377294d18f7e96f829ead20a8a3c212bce10fee2337ea8279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
